# -*- coding: utf-8 -*-
"""movies_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sb2kC5nFK7UqxQyrswczfYdj9mHm__DX
"""

import pandas as pd

data = pd.read_csv("/content/movies.csv")

data.info()

data.head()

print(data.shape)

data.columns

data.tail()

data.isna().sum()

data=data.drop("Gross", axis=1)

data.isna().sum()

data=data.drop("RunTime",axis=1)

data=data.dropna()

data.isna().sum()

data.info()

data.duplicated().sum()

data.drop_duplicates(inplace=True)

data.duplicated().sum()

data.head(25)

data['GENRE']= data['GENRE'].str.strip()

data.head()

data['ONE-LINE']= data['ONE-LINE'].str.strip()
data['STARS']= data['STARS'].str.strip()

data.head()

data["YEAR"] = data["YEAR"].str.replace('(', '')
data["YEAR"] = data["YEAR"].str.replace(')', '')

data.head()

data['YEAR']=data['YEAR'].str.strip()

data["YEAR"] = data["YEAR"].str.replace('-', '')

# data=data.drop("END-YEAR", axis = 1)

# data[['STARR-YEAR','END-YEAR',]] = data['YEAR'].str.split('-',expand=True)



data.head()

data[['Genre1','Genre2','Genre3']] = data['GENRE'].str.split(',',expand=True)

data.head()

# data['STARS'] = data['STARS'].str.strip('\n')
data[['Director', 'Actor']] = data['STARS'].str.split('|', expand=True)

data.head()

for idx, value in data['Director'].iteritems():
    if 'Stars:' in value:
        data['Actor'][idx], data['Director'][idx] = value, ''

data.head()

data['Director'] = data['Director'].str.replace('Director:', '')
data['Director'] = data['Director'].str.replace('Directors:', '')
data['Actor'] = data['Actor'].str.replace('Stars:', '')
data['Actor'] = data['Actor'].str.replace('Star:', '')

data['Director'] = data['Director'].str.strip()
data['Actor'] = data['Actor'].str.strip()
data['Actor'] = data['Actor'].str.replace('\n', '')

data.head()

data.isnull().sum()
data.info()

data=data.drop("STARS",axis=1)

data.head(50)

data.describe()

data['VOTES'].describe()

data["VOTES"] = data["VOTES"].str.replace(',', '')

data['VOTES']=data['VOTES'].astype(int)

data.describe()

data.info()

print(data['GENRE'].value_counts())

# data=data.drop('GENRE', axis=1)

print(data['Genre1'].value_counts())
print(data['Genre2'].value_counts())
print(data['Genre3'].value_counts())

data.head()

data['Director'].describe()

